---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse

- src: git@github.com:Myash-New/Vector-role.git
  scm: git
  version: "main"
  name: vector

- src: git@github.com:Myash-New/Lighthouse-role.git
  scm: git
  version: "main"
  name: lighthouse
