- name: Converge
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Ensure Vector directory exists
      ansible.builtin.file:
        path: "/etc/vector"
        state: directory
        mode: "0755"

    - name: Template vector config
      ansible.builtin.template:
        src: templates/vector.conf.j2
        dest: /etc/vector/vector.conf

    - name: Install Vector (placeholder)
      ansible.builtin.shell: echo "Installing Vector..."
