---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: geerlingguy/docker-centos7-ansible:latest
    pre_build_image: true
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
async: 7200
poll: 0
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
