---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

  - name: debian
    image: geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  become: false
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
  config_options:
    defaults:
      timeout: 60
      command_timeout: 600
    ssh_connection:
      host_key_checking: false

verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - verify
    - destroy